### ISSUE TITLE
Additional components, Collapse

### ISSUE THREAD

**Issue by Margino** [15web/web-accessibility#2]
Здравствуйте. Вы применяете атрибут `aria-expanded` в Additional components, Collapse к блоку который сворачивается. Могу ошибаться, но разве `aria-expanded` применяется не к кнопке?

https://github.com/15web/web-accessibility/blob/master/docs/additional.html#L649-L655

**Comment by mixrich** [comment]
@Margino Алексей, спасибо за замечание. Освежили в памяти документацию https://www.w3.org/TR/wai-aria/states_and_properties#aria-expanded и обнаружили, что действительно некорректно применяли данный атрибут

**Comment by Margino** [comment]
@mixrich Михаил, пожалуйста, был рад помочь в хорошем деле.

**Comment by mixrich** [comment]
Актуализировали collapse в ветке master.
